# -*- coding: utf-8 -*-
"""Android version of the 118-element periodic-table app.
Built with Kivy. Touch a cell to show both the element tooltip and the
purple group-calculation tooltip.
"""
import re
from kivy.app import App
from kivy.core.window import Window
from kivy.metrics import dp, sp
from kivy.properties import NumericProperty, StringProperty, ListProperty, BooleanProperty
from kivy.uix.behaviors import ButtonBehavior
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.button import Button
from kivy.uix.gridlayout import GridLayout
from kivy.uix.label import Label
from kivy.uix.relativelayout import RelativeLayout
from kivy.uix.scrollview import ScrollView
from kivy.uix.widget import Widget
from kivy.uix.modalview import ModalView
from kivy.graphics import Color, RoundedRectangle, Line

# ---------------- data ----------------
ELEMENTS = [{'z': 1,
  'symbol': 'H',
  'name': 'Hydrogen',
  'name_fa': 'هیدروژن',
  'category': 'nonmetal',
  'category_fa': 'نافلز',
  'group': 1,
  'group_text': '1',
  'period': 1,
  'config': '1s1',
  'mass': 1},
 {'z': 2,
  'symbol': 'He',
  'name': 'Helium',
  'name_fa': 'هلیم',
  'category': 'noble gas',
  'category_fa': 'گاز نجیب',
  'group': 18,
  'group_text': '18',
  'period': 1,
  'config': '1s2',
  'mass': 4},
 {'z': 3,
  'symbol': 'Li',
  'name': 'Lithium',
  'name_fa': 'لیتیوم',
  'category': 'alkali metal',
  'category_fa': 'فلز قلیایی',
  'group': 1,
  'group_text': '1',
  'period': 2,
  'config': '[He] 2s1',
  'mass': 7},
 {'z': 4,
  'symbol': 'Be',
  'name': 'Beryllium',
  'name_fa': 'بریلیم',
  'category': 'alkaline earth metal',
  'category_fa': 'فلز قلیایی خاکی',
  'group': 2,
  'group_text': '2',
  'period': 2,
  'config': '[He] 2s2',
  'mass': 9},
 {'z': 5,
  'symbol': 'B',
  'name': 'Boron',
  'name_fa': 'بور',
  'category': 'metalloid',
  'category_fa': 'شبه\u200cفلز',
  'group': 13,
  'group_text': '13',
  'period': 2,
  'config': '[He] 2s2 2p1',
  'mass': 11},
 {'z': 6,
  'symbol': 'C',
  'name': 'Carbon',
  'name_fa': 'کربن',
  'category': 'nonmetal',
  'category_fa': 'نافلز',
  'group': 14,
  'group_text': '14',
  'period': 2,
  'config': '[He] 2s2 2p2',
  'mass': 12},
 {'z': 7,
  'symbol': 'N',
  'name': 'Nitrogen',
  'name_fa': 'نیتروژن',
  'category': 'nonmetal',
  'category_fa': 'نافلز',
  'group': 15,
  'group_text': '15',
  'period': 2,
  'config': '[He] 2s2 2p3',
  'mass': 14},
 {'z': 8,
  'symbol': 'O',
  'name': 'Oxygen',
  'name_fa': 'اکسیژن',
  'category': 'nonmetal',
  'category_fa': 'نافلز',
  'group': 16,
  'group_text': '16',
  'period': 2,
  'config': '[He] 2s2 2p4',
  'mass': 16},
 {'z': 9,
  'symbol': 'F',
  'name': 'Fluorine',
  'name_fa': 'فلوئور',
  'category': 'halogen',
  'category_fa': 'هالوژن',
  'group': 17,
  'group_text': '17',
  'period': 2,
  'config': '[He] 2s2 2p5',
  'mass': 19},
 {'z': 10,
  'symbol': 'Ne',
  'name': 'Neon',
  'name_fa': 'نئون',
  'category': 'noble gas',
  'category_fa': 'گاز نجیب',
  'group': 18,
  'group_text': '18',
  'period': 2,
  'config': '[He] 2s2 2p6',
  'mass': 20},
 {'z': 11,
  'symbol': 'Na',
  'name': 'Sodium',
  'name_fa': 'سدیم',
  'category': 'alkali metal',
  'category_fa': 'فلز قلیایی',
  'group': 1,
  'group_text': '1',
  'period': 3,
  'config': '[Ne] 3s1',
  'mass': 23},
 {'z': 12,
  'symbol': 'Mg',
  'name': 'Magnesium',
  'name_fa': 'منیزیم',
  'category': 'alkaline earth metal',
  'category_fa': 'فلز قلیایی خاکی',
  'group': 2,
  'group_text': '2',
  'period': 3,
  'config': '[Ne] 3s2',
  'mass': 24},
 {'z': 13,
  'symbol': 'Al',
  'name': 'Aluminium',
  'name_fa': 'آلومینیوم',
  'category': 'post-transition metal',
  'category_fa': 'فلز پس\u200cواسطه',
  'group': 13,
  'group_text': '13',
  'period': 3,
  'config': '[Ne] 3s2 3p1',
  'mass': 27},
 {'z': 14,
  'symbol': 'Si',
  'name': 'Silicon',
  'name_fa': 'سیلیسیم',
  'category': 'metalloid',
  'category_fa': 'شبه\u200cفلز',
  'group': 14,
  'group_text': '14',
  'period': 3,
  'config': '[Ne] 3s2 3p2',
  'mass': 28},
 {'z': 15,
  'symbol': 'P',
  'name': 'Phosphorus',
  'name_fa': 'فسفر',
  'category': 'nonmetal',
  'category_fa': 'نافلز',
  'group': 15,
  'group_text': '15',
  'period': 3,
  'config': '[Ne] 3s2 3p3',
  'mass': 31},
 {'z': 16,
  'symbol': 'S',
  'name': 'Sulfur',
  'name_fa': 'گوگرد',
  'category': 'nonmetal',
  'category_fa': 'نافلز',
  'group': 16,
  'group_text': '16',
  'period': 3,
  'config': '[Ne] 3s2 3p4',
  'mass': 32},
 {'z': 17,
  'symbol': 'Cl',
  'name': 'Chlorine',
  'name_fa': 'کلر',
  'category': 'halogen',
  'category_fa': 'هالوژن',
  'group': 17,
  'group_text': '17',
  'period': 3,
  'config': '[Ne] 3s2 3p5',
  'mass': 35},
 {'z': 18,
  'symbol': 'Ar',
  'name': 'Argon',
  'name_fa': 'آرگون',
  'category': 'noble gas',
  'category_fa': 'گاز نجیب',
  'group': 18,
  'group_text': '18',
  'period': 3,
  'config': '[Ne] 3s2 3p6',
  'mass': 40},
 {'z': 19,
  'symbol': 'K',
  'name': 'Potassium',
  'name_fa': 'پتاسیم',
  'category': 'alkali metal',
  'category_fa': 'فلز قلیایی',
  'group': 1,
  'group_text': '1',
  'period': 4,
  'config': '[Ar] 4s1',
  'mass': 39},
 {'z': 20,
  'symbol': 'Ca',
  'name': 'Calcium',
  'name_fa': 'کلسیم',
  'category': 'alkaline earth metal',
  'category_fa': 'فلز قلیایی خاکی',
  'group': 2,
  'group_text': '2',
  'period': 4,
  'config': '[Ar] 4s2',
  'mass': 40},
 {'z': 21,
  'symbol': 'Sc',
  'name': 'Scandium',
  'name_fa': 'اسکاندیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 3,
  'group_text': '3',
  'period': 4,
  'config': '[Ar] 3d1 4s2',
  'mass': 45},
 {'z': 22,
  'symbol': 'Ti',
  'name': 'Titanium',
  'name_fa': 'تیتانیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 4,
  'group_text': '4',
  'period': 4,
  'config': '[Ar] 3d2 4s2',
  'mass': 48},
 {'z': 23,
  'symbol': 'V',
  'name': 'Vanadium',
  'name_fa': 'وانادیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 5,
  'group_text': '5',
  'period': 4,
  'config': '[Ar] 3d3 4s2',
  'mass': 51},
 {'z': 24,
  'symbol': 'Cr',
  'name': 'Chromium',
  'name_fa': 'کروم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 6,
  'group_text': '6',
  'period': 4,
  'config': '[Ar] 3d5 4s1',
  'mass': 52},
 {'z': 25,
  'symbol': 'Mn',
  'name': 'Manganese',
  'name_fa': 'منگنز',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 7,
  'group_text': '7',
  'period': 4,
  'config': '[Ar] 3d5 4s2',
  'mass': 55},
 {'z': 26,
  'symbol': 'Fe',
  'name': 'Iron',
  'name_fa': 'آهن',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 8,
  'group_text': '8',
  'period': 4,
  'config': '[Ar] 3d6 4s2',
  'mass': 56},
 {'z': 27,
  'symbol': 'Co',
  'name': 'Cobalt',
  'name_fa': 'کبالت',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 9,
  'group_text': '9',
  'period': 4,
  'config': '[Ar] 3d7 4s2',
  'mass': 59},
 {'z': 28,
  'symbol': 'Ni',
  'name': 'Nickel',
  'name_fa': 'نیکل',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 10,
  'group_text': '10',
  'period': 4,
  'config': '[Ar] 3d8 4s2',
  'mass': 58},
 {'z': 29,
  'symbol': 'Cu',
  'name': 'Copper',
  'name_fa': 'مس',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 11,
  'group_text': '11',
  'period': 4,
  'config': '[Ar] 3d10 4s1',
  'mass': 63},
 {'z': 30,
  'symbol': 'Zn',
  'name': 'Zinc',
  'name_fa': 'روی',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 12,
  'group_text': '12',
  'period': 4,
  'config': '[Ar] 3d10 4s2',
  'mass': 64},
 {'z': 31,
  'symbol': 'Ga',
  'name': 'Gallium',
  'name_fa': 'گالیم',
  'category': 'post-transition metal',
  'category_fa': 'فلز پس\u200cواسطه',
  'group': 13,
  'group_text': '13',
  'period': 4,
  'config': '[Ar] 3d10 4s2 4p1',
  'mass': 69},
 {'z': 32,
  'symbol': 'Ge',
  'name': 'Germanium',
  'name_fa': 'ژرمانیم',
  'category': 'metalloid',
  'category_fa': 'شبه\u200cفلز',
  'group': 14,
  'group_text': '14',
  'period': 4,
  'config': '[Ar] 3d10 4s2 4p2',
  'mass': 74},
 {'z': 33,
  'symbol': 'As',
  'name': 'Arsenic',
  'name_fa': 'آرسنیک',
  'category': 'metalloid',
  'category_fa': 'شبه\u200cفلز',
  'group': 15,
  'group_text': '15',
  'period': 4,
  'config': '[Ar] 3d10 4s2 4p3',
  'mass': 75},
 {'z': 34,
  'symbol': 'Se',
  'name': 'Selenium',
  'name_fa': 'سلنیم',
  'category': 'nonmetal',
  'category_fa': 'نافلز',
  'group': 16,
  'group_text': '16',
  'period': 4,
  'config': '[Ar] 3d10 4s2 4p4',
  'mass': 80},
 {'z': 35,
  'symbol': 'Br',
  'name': 'Bromine',
  'name_fa': 'برم',
  'category': 'halogen',
  'category_fa': 'هالوژن',
  'group': 17,
  'group_text': '17',
  'period': 4,
  'config': '[Ar] 3d10 4s2 4p5',
  'mass': 79},
 {'z': 36,
  'symbol': 'Kr',
  'name': 'Krypton',
  'name_fa': 'کریپتون',
  'category': 'noble gas',
  'category_fa': 'گاز نجیب',
  'group': 18,
  'group_text': '18',
  'period': 4,
  'config': '[Ar] 3d10 4s2 4p6',
  'mass': 84},
 {'z': 37,
  'symbol': 'Rb',
  'name': 'Rubidium',
  'name_fa': 'روبیدیم',
  'category': 'alkali metal',
  'category_fa': 'فلز قلیایی',
  'group': 1,
  'group_text': '1',
  'period': 5,
  'config': '[Kr] 5s1',
  'mass': 85},
 {'z': 38,
  'symbol': 'Sr',
  'name': 'Strontium',
  'name_fa': 'استرانسیم',
  'category': 'alkaline earth metal',
  'category_fa': 'فلز قلیایی خاکی',
  'group': 2,
  'group_text': '2',
  'period': 5,
  'config': '[Kr] 5s2',
  'mass': 88},
 {'z': 39,
  'symbol': 'Y',
  'name': 'Yttrium',
  'name_fa': 'ایتریم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 3,
  'group_text': '3',
  'period': 5,
  'config': '[Kr] 4d1 5s2',
  'mass': 89},
 {'z': 40,
  'symbol': 'Zr',
  'name': 'Zirconium',
  'name_fa': 'زیرکونیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 4,
  'group_text': '4',
  'period': 5,
  'config': '[Kr] 4d2 5s2',
  'mass': 90},
 {'z': 41,
  'symbol': 'Nb',
  'name': 'Niobium',
  'name_fa': 'نیوبیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 5,
  'group_text': '5',
  'period': 5,
  'config': '[Kr] 4d4 5s1',
  'mass': 93},
 {'z': 42,
  'symbol': 'Mo',
  'name': 'Molybdenum',
  'name_fa': 'مولیبدن',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 6,
  'group_text': '6',
  'period': 5,
  'config': '[Kr] 4d5 5s1',
  'mass': 98},
 {'z': 43,
  'symbol': 'Tc',
  'name': 'Technetium',
  'name_fa': 'تکنسیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 7,
  'group_text': '7',
  'period': 5,
  'config': '[Kr] 4d5 5s2',
  'mass': 98},
 {'z': 44,
  'symbol': 'Ru',
  'name': 'Ruthenium',
  'name_fa': 'روتنیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 8,
  'group_text': '8',
  'period': 5,
  'config': '[Kr] 4d7 5s1',
  'mass': 101},
 {'z': 45,
  'symbol': 'Rh',
  'name': 'Rhodium',
  'name_fa': 'رودیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 9,
  'group_text': '9',
  'period': 5,
  'config': '[Kr] 4d8 5s1',
  'mass': 103},
 {'z': 46,
  'symbol': 'Pd',
  'name': 'Palladium',
  'name_fa': 'پالادیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 10,
  'group_text': '10',
  'period': 5,
  'config': '[Kr] 4d10',
  'mass': 106},
 {'z': 47,
  'symbol': 'Ag',
  'name': 'Silver',
  'name_fa': 'نقره',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 11,
  'group_text': '11',
  'period': 5,
  'config': '[Kr] 4d10 5s1',
  'mass': 107},
 {'z': 48,
  'symbol': 'Cd',
  'name': 'Cadmium',
  'name_fa': 'کادمیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 12,
  'group_text': '12',
  'period': 5,
  'config': '[Kr] 4d10 5s2',
  'mass': 114},
 {'z': 49,
  'symbol': 'In',
  'name': 'Indium',
  'name_fa': 'ایندیم',
  'category': 'post-transition metal',
  'category_fa': 'فلز پس\u200cواسطه',
  'group': 13,
  'group_text': '13',
  'period': 5,
  'config': '[Kr] 4d10 5s2 5p1',
  'mass': 115},
 {'z': 50,
  'symbol': 'Sn',
  'name': 'Tin',
  'name_fa': 'قلع',
  'category': 'post-transition metal',
  'category_fa': 'فلز پس\u200cواسطه',
  'group': 14,
  'group_text': '14',
  'period': 5,
  'config': '[Kr] 4d10 5s2 5p2',
  'mass': 120},
 {'z': 51,
  'symbol': 'Sb',
  'name': 'Antimony',
  'name_fa': 'آنتیموان',
  'category': 'metalloid',
  'category_fa': 'شبه\u200cفلز',
  'group': 15,
  'group_text': '15',
  'period': 5,
  'config': '[Kr] 4d10 5s2 5p3',
  'mass': 121},
 {'z': 52,
  'symbol': 'Te',
  'name': 'Tellurium',
  'name_fa': 'تلوریم',
  'category': 'metalloid',
  'category_fa': 'شبه\u200cفلز',
  'group': 16,
  'group_text': '16',
  'period': 5,
  'config': '[Kr] 4d10 5s2 5p4',
  'mass': 130},
 {'z': 53,
  'symbol': 'I',
  'name': 'Iodine',
  'name_fa': 'ید',
  'category': 'halogen',
  'category_fa': 'هالوژن',
  'group': 17,
  'group_text': '17',
  'period': 5,
  'config': '[Kr] 4d10 5s2 5p5',
  'mass': 127},
 {'z': 54,
  'symbol': 'Xe',
  'name': 'Xenon',
  'name_fa': 'زنون',
  'category': 'noble gas',
  'category_fa': 'گاز نجیب',
  'group': 18,
  'group_text': '18',
  'period': 5,
  'config': '[Kr] 4d10 5s2 5p6',
  'mass': 131},
 {'z': 55,
  'symbol': 'Cs',
  'name': 'Caesium',
  'name_fa': 'سزیم',
  'category': 'alkali metal',
  'category_fa': 'فلز قلیایی',
  'group': 1,
  'group_text': '1',
  'period': 6,
  'config': '[Xe] 6s1',
  'mass': 133},
 {'z': 56,
  'symbol': 'Ba',
  'name': 'Barium',
  'name_fa': 'باریم',
  'category': 'alkaline earth metal',
  'category_fa': 'فلز قلیایی خاکی',
  'group': 2,
  'group_text': '2',
  'period': 6,
  'config': '[Xe] 6s2',
  'mass': 138},
 {'z': 57,
  'symbol': 'La',
  'name': 'Lanthanum',
  'name_fa': 'لانتان',
  'category': 'lanthanide',
  'category_fa': 'لانتانید',
  'group': 3,
  'group_text': '—',
  'period': 6,
  'config': '[Xe] 5d1 6s2',
  'mass': 139},
 {'z': 58,
  'symbol': 'Ce',
  'name': 'Cerium',
  'name_fa': 'سریم',
  'category': 'lanthanide',
  'category_fa': 'لانتانید',
  'group': 4,
  'group_text': '—',
  'period': 6,
  'config': '[Xe] 4f1 5d1 6s2',
  'mass': 140},
 {'z': 59,
  'symbol': 'Pr',
  'name': 'Praseodymium',
  'name_fa': 'پرازئودیمیم',
  'category': 'lanthanide',
  'category_fa': 'لانتانید',
  'group': 5,
  'group_text': '—',
  'period': 6,
  'config': '[Xe] 4f3 6s2',
  'mass': 141},
 {'z': 60,
  'symbol': 'Nd',
  'name': 'Neodymium',
  'name_fa': 'نئودیمیم',
  'category': 'lanthanide',
  'category_fa': 'لانتانید',
  'group': 6,
  'group_text': '—',
  'period': 6,
  'config': '[Xe] 4f4 6s2',
  'mass': 142},
 {'z': 61,
  'symbol': 'Pm',
  'name': 'Promethium',
  'name_fa': 'پرومتیم',
  'category': 'lanthanide',
  'category_fa': 'لانتانید',
  'group': 7,
  'group_text': '—',
  'period': 6,
  'config': '[Xe] 4f5 6s2',
  'mass': 145},
 {'z': 62,
  'symbol': 'Sm',
  'name': 'Samarium',
  'name_fa': 'ساماریم',
  'category': 'lanthanide',
  'category_fa': 'لانتانید',
  'group': 8,
  'group_text': '—',
  'period': 6,
  'config': '[Xe] 4f6 6s2',
  'mass': 152},
 {'z': 63,
  'symbol': 'Eu',
  'name': 'Europium',
  'name_fa': 'یوروپیم',
  'category': 'lanthanide',
  'category_fa': 'لانتانید',
  'group': 9,
  'group_text': '—',
  'period': 6,
  'config': '[Xe] 4f7 6s2',
  'mass': 153},
 {'z': 64,
  'symbol': 'Gd',
  'name': 'Gadolinium',
  'name_fa': 'گادولینیم',
  'category': 'lanthanide',
  'category_fa': 'لانتانید',
  'group': 10,
  'group_text': '—',
  'period': 6,
  'config': '[Xe] 4f7 5d1 6s2',
  'mass': 158},
 {'z': 65,
  'symbol': 'Tb',
  'name': 'Terbium',
  'name_fa': 'تربیم',
  'category': 'lanthanide',
  'category_fa': 'لانتانید',
  'group': 11,
  'group_text': '—',
  'period': 6,
  'config': '[Xe] 4f9 6s2',
  'mass': 159},
 {'z': 66,
  'symbol': 'Dy',
  'name': 'Dysprosium',
  'name_fa': 'دیسپروزیم',
  'category': 'lanthanide',
  'category_fa': 'لانتانید',
  'group': 12,
  'group_text': '—',
  'period': 6,
  'config': '[Xe] 4f10 6s2',
  'mass': 164},
 {'z': 67,
  'symbol': 'Ho',
  'name': 'Holmium',
  'name_fa': 'هولمیم',
  'category': 'lanthanide',
  'category_fa': 'لانتانید',
  'group': 13,
  'group_text': '—',
  'period': 6,
  'config': '[Xe] 4f11 6s2',
  'mass': 165},
 {'z': 68,
  'symbol': 'Er',
  'name': 'Erbium',
  'name_fa': 'اربیوم',
  'category': 'lanthanide',
  'category_fa': 'لانتانید',
  'group': 14,
  'group_text': '—',
  'period': 6,
  'config': '[Xe] 4f12 6s2',
  'mass': 166},
 {'z': 69,
  'symbol': 'Tm',
  'name': 'Thulium',
  'name_fa': 'تولیم',
  'category': 'lanthanide',
  'category_fa': 'لانتانید',
  'group': 15,
  'group_text': '—',
  'period': 6,
  'config': '[Xe] 4f13 6s2',
  'mass': 169},
 {'z': 70,
  'symbol': 'Yb',
  'name': 'Ytterbium',
  'name_fa': 'ایتربیم',
  'category': 'lanthanide',
  'category_fa': 'لانتانید',
  'group': 16,
  'group_text': '—',
  'period': 6,
  'config': '[Xe] 4f14 6s2',
  'mass': 174},
 {'z': 71,
  'symbol': 'Lu',
  'name': 'Lutetium',
  'name_fa': 'لوتتیم',
  'category': 'lanthanide',
  'category_fa': 'لانتانید',
  'group': 17,
  'group_text': '—',
  'period': 6,
  'config': '[Xe] 4f14 5d1 6s2',
  'mass': 175},
 {'z': 72,
  'symbol': 'Hf',
  'name': 'Hafnium',
  'name_fa': 'هافنیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 4,
  'group_text': '4',
  'period': 6,
  'config': '[Xe] 4f14 5d2 6s2',
  'mass': 178},
 {'z': 73,
  'symbol': 'Ta',
  'name': 'Tantalum',
  'name_fa': 'تانتال',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 5,
  'group_text': '5',
  'period': 6,
  'config': '[Xe] 4f14 5d3 6s2',
  'mass': 181},
 {'z': 74,
  'symbol': 'W',
  'name': 'Tungsten',
  'name_fa': 'تنگستن',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 6,
  'group_text': '6',
  'period': 6,
  'config': '[Xe] 4f14 5d4 6s2',
  'mass': 184},
 {'z': 75,
  'symbol': 'Re',
  'name': 'Rhenium',
  'name_fa': 'رنیوم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 7,
  'group_text': '7',
  'period': 6,
  'config': '[Xe] 4f14 5d5 6s2',
  'mass': 187},
 {'z': 76,
  'symbol': 'Os',
  'name': 'Osmium',
  'name_fa': 'اُسمیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 8,
  'group_text': '8',
  'period': 6,
  'config': '[Xe] 4f14 5d6 6s2',
  'mass': 192},
 {'z': 77,
  'symbol': 'Ir',
  'name': 'Iridium',
  'name_fa': 'ایریدیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 9,
  'group_text': '9',
  'period': 6,
  'config': '[Xe] 4f14 5d7 6s2',
  'mass': 193},
 {'z': 78,
  'symbol': 'Pt',
  'name': 'Platinum',
  'name_fa': 'پلاتین',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 10,
  'group_text': '10',
  'period': 6,
  'config': '[Xe] 4f14 5d9 6s1',
  'mass': 195},
 {'z': 79,
  'symbol': 'Au',
  'name': 'Gold',
  'name_fa': 'طلا',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 11,
  'group_text': '11',
  'period': 6,
  'config': '[Xe] 4f14 5d10 6s1',
  'mass': 197},
 {'z': 80,
  'symbol': 'Hg',
  'name': 'Mercury',
  'name_fa': 'جیوه',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 12,
  'group_text': '12',
  'period': 6,
  'config': '[Xe] 4f14 5d10 6s2',
  'mass': 202},
 {'z': 81,
  'symbol': 'Tl',
  'name': 'Thallium',
  'name_fa': 'تالیم',
  'category': 'post-transition metal',
  'category_fa': 'فلز پس\u200cواسطه',
  'group': 13,
  'group_text': '13',
  'period': 6,
  'config': '[Xe] 4f14 5d10 6s2 6p1',
  'mass': 205},
 {'z': 82,
  'symbol': 'Pb',
  'name': 'Lead',
  'name_fa': 'سرب',
  'category': 'post-transition metal',
  'category_fa': 'فلز پس\u200cواسطه',
  'group': 14,
  'group_text': '14',
  'period': 6,
  'config': '[Xe] 4f14 5d10 6s2 6p2',
  'mass': 208},
 {'z': 83,
  'symbol': 'Bi',
  'name': 'Bismuth',
  'name_fa': 'بیسموت',
  'category': 'post-transition metal',
  'category_fa': 'فلز پس\u200cواسطه',
  'group': 15,
  'group_text': '15',
  'period': 6,
  'config': '[Xe] 4f14 5d10 6s2 6p3',
  'mass': 209},
 {'z': 84,
  'symbol': 'Po',
  'name': 'Polonium',
  'name_fa': 'پولونیم',
  'category': 'post-transition metal',
  'category_fa': 'فلز پس\u200cواسطه',
  'group': 16,
  'group_text': '16',
  'period': 6,
  'config': '[Xe] 4f14 5d10 6s2 6p4',
  'mass': 209},
 {'z': 85,
  'symbol': 'At',
  'name': 'Astatine',
  'name_fa': 'آستاتین',
  'category': 'halogen',
  'category_fa': 'هالوژن',
  'group': 17,
  'group_text': '17',
  'period': 6,
  'config': '[Xe] 4f14 5d10 6s2 6p5',
  'mass': 210},
 {'z': 86,
  'symbol': 'Rn',
  'name': 'Radon',
  'name_fa': 'رادون',
  'category': 'noble gas',
  'category_fa': 'گاز نجیب',
  'group': 18,
  'group_text': '18',
  'period': 6,
  'config': '[Xe] 4f14 5d10 6s2 6p6',
  'mass': 222},
 {'z': 87,
  'symbol': 'Fr',
  'name': 'Francium',
  'name_fa': 'فرانسیم',
  'category': 'alkali metal',
  'category_fa': 'فلز قلیایی',
  'group': 1,
  'group_text': '1',
  'period': 7,
  'config': '[Rn] 7s1',
  'mass': 223},
 {'z': 88,
  'symbol': 'Ra',
  'name': 'Radium',
  'name_fa': 'رادیم',
  'category': 'alkaline earth metal',
  'category_fa': 'فلز قلیایی خاکی',
  'group': 2,
  'group_text': '2',
  'period': 7,
  'config': '[Rn] 7s2',
  'mass': 226},
 {'z': 89,
  'symbol': 'Ac',
  'name': 'Actinium',
  'name_fa': 'اکتینیم',
  'category': 'actinide',
  'category_fa': 'اکتینید',
  'group': 3,
  'group_text': '—',
  'period': 7,
  'config': '[Rn] 6d1 7s2',
  'mass': 227},
 {'z': 90,
  'symbol': 'Th',
  'name': 'Thorium',
  'name_fa': 'توریم',
  'category': 'actinide',
  'category_fa': 'اکتینید',
  'group': 4,
  'group_text': '—',
  'period': 7,
  'config': '[Rn] 6d2 7s2',
  'mass': 232},
 {'z': 91,
  'symbol': 'Pa',
  'name': 'Protactinium',
  'name_fa': 'پروتاکتینیم',
  'category': 'actinide',
  'category_fa': 'اکتینید',
  'group': 5,
  'group_text': '—',
  'period': 7,
  'config': '[Rn] 5f2 6d1 7s2',
  'mass': 231},
 {'z': 92,
  'symbol': 'U',
  'name': 'Uranium',
  'name_fa': 'اورانیم',
  'category': 'actinide',
  'category_fa': 'اکتینید',
  'group': 6,
  'group_text': '—',
  'period': 7,
  'config': '[Rn] 5f3 6d1 7s2',
  'mass': 238},
 {'z': 93,
  'symbol': 'Np',
  'name': 'Neptunium',
  'name_fa': 'نپتونیم',
  'category': 'actinide',
  'category_fa': 'اکتینید',
  'group': 7,
  'group_text': '—',
  'period': 7,
  'config': '[Rn] 5f4 6d1 7s2',
  'mass': 237},
 {'z': 94,
  'symbol': 'Pu',
  'name': 'Plutonium',
  'name_fa': 'پلوتونیم',
  'category': 'actinide',
  'category_fa': 'اکتینید',
  'group': 8,
  'group_text': '—',
  'period': 7,
  'config': '[Rn] 5f6 7s2',
  'mass': 244},
 {'z': 95,
  'symbol': 'Am',
  'name': 'Americium',
  'name_fa': 'آمریسیم',
  'category': 'actinide',
  'category_fa': 'اکتینید',
  'group': 9,
  'group_text': '—',
  'period': 7,
  'config': '[Rn] 5f7 7s2',
  'mass': 243},
 {'z': 96,
  'symbol': 'Cm',
  'name': 'Curium',
  'name_fa': 'کوریوم',
  'category': 'actinide',
  'category_fa': 'اکتینید',
  'group': 10,
  'group_text': '—',
  'period': 7,
  'config': '[Rn] 5f7 6d1 7s2',
  'mass': 247},
 {'z': 97,
  'symbol': 'Bk',
  'name': 'Berkelium',
  'name_fa': 'برکلیم',
  'category': 'actinide',
  'category_fa': 'اکتینید',
  'group': 11,
  'group_text': '—',
  'period': 7,
  'config': '[Rn] 5f9 7s2',
  'mass': 247},
 {'z': 98,
  'symbol': 'Cf',
  'name': 'Californium',
  'name_fa': 'کالیفرنیم',
  'category': 'actinide',
  'category_fa': 'اکتینید',
  'group': 12,
  'group_text': '—',
  'period': 7,
  'config': '[Rn] 5f10 7s2',
  'mass': 251},
 {'z': 99,
  'symbol': 'Es',
  'name': 'Einsteinium',
  'name_fa': 'اینشتینیم',
  'category': 'actinide',
  'category_fa': 'اکتینید',
  'group': 13,
  'group_text': '—',
  'period': 7,
  'config': '[Rn] 5f11 7s2',
  'mass': 252},
 {'z': 100,
  'symbol': 'Fm',
  'name': 'Fermium',
  'name_fa': 'فرمیم',
  'category': 'actinide',
  'category_fa': 'اکتینید',
  'group': 14,
  'group_text': '—',
  'period': 7,
  'config': '[Rn] 5f12 7s2',
  'mass': 257},
 {'z': 101,
  'symbol': 'Md',
  'name': 'Mendelevium',
  'name_fa': 'مندلیفیم',
  'category': 'actinide',
  'category_fa': 'اکتینید',
  'group': 15,
  'group_text': '—',
  'period': 7,
  'config': '[Rn] 5f13 7s2',
  'mass': 258},
 {'z': 102,
  'symbol': 'No',
  'name': 'Nobelium',
  'name_fa': 'نوبلیم',
  'category': 'actinide',
  'category_fa': 'اکتینید',
  'group': 16,
  'group_text': '—',
  'period': 7,
  'config': '[Rn] 5f14 7s2',
  'mass': 259},
 {'z': 103,
  'symbol': 'Lr',
  'name': 'Lawrencium',
  'name_fa': 'لارنسیم',
  'category': 'actinide',
  'category_fa': 'اکتینید',
  'group': 17,
  'group_text': '—',
  'period': 7,
  'config': '[Rn] 5f14 7s2 7p1',
  'mass': 262},
 {'z': 104,
  'symbol': 'Rf',
  'name': 'Rutherfordium',
  'name_fa': 'رادرفوردیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 4,
  'group_text': '4',
  'period': 7,
  'config': '[Rn] 5f14 6d2 7s2',
  'mass': 267},
 {'z': 105,
  'symbol': 'Db',
  'name': 'Dubnium',
  'name_fa': 'دوبنیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 5,
  'group_text': '5',
  'period': 7,
  'config': '[Rn] 5f14 6d3 7s2',
  'mass': 268},
 {'z': 106,
  'symbol': 'Sg',
  'name': 'Seaborgium',
  'name_fa': 'سیبورگیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 6,
  'group_text': '6',
  'period': 7,
  'config': '[Rn] 5f14 6d4 7s2',
  'mass': 269},
 {'z': 107,
  'symbol': 'Bh',
  'name': 'Bohrium',
  'name_fa': 'بوریم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 7,
  'group_text': '7',
  'period': 7,
  'config': '[Rn] 5f14 6d5 7s2',
  'mass': 270},
 {'z': 108,
  'symbol': 'Hs',
  'name': 'Hassium',
  'name_fa': 'هاسیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 8,
  'group_text': '8',
  'period': 7,
  'config': '[Rn] 5f14 6d6 7s2',
  'mass': 277},
 {'z': 109,
  'symbol': 'Mt',
  'name': 'Meitnerium',
  'name_fa': 'مایتنریم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 9,
  'group_text': '9',
  'period': 7,
  'config': '[Rn] 5f14 6d7 7s2',
  'mass': 278},
 {'z': 110,
  'symbol': 'Ds',
  'name': 'Darmstadtium',
  'name_fa': 'دارمشتادیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 10,
  'group_text': '10',
  'period': 7,
  'config': '[Rn] 5f14 6d9 7s1',
  'mass': 281},
 {'z': 111,
  'symbol': 'Rg',
  'name': 'Roentgenium',
  'name_fa': 'رونتگنیم',
  'category': 'transition metal',
  'category_fa': 'فلز واسطه',
  'group': 11,
  'group_text': '11',
  'period': 7,
  'config': '[Rn] 5f14 6d10 7s1',
  'mass': 282},
 {'z': 112,
  'symbol': 'Cn',
  'name': 'Copernicium',
  'name_fa': 'کوپرنیسیم',
  'category': 'post-transition metal',
  'category_fa': 'فلز پس\u200cواسطه',
  'group': 12,
  'group_text': '12',
  'period': 7,
  'config': '[Rn] 5f14 6d10 7s2',
  'mass': 285},
 {'z': 113,
  'symbol': 'Nh',
  'name': 'Nihonium',
  'name_fa': 'نیهونیوم',
  'category': 'post-transition metal',
  'category_fa': 'فلز پس\u200cواسطه',
  'group': 13,
  'group_text': '13',
  'period': 7,
  'config': '[Rn] 5f14 6d10 7s2 7p1',
  'mass': 286},
 {'z': 114,
  'symbol': 'Fl',
  'name': 'Flerovium',
  'name_fa': 'فلروویم',
  'category': 'post-transition metal',
  'category_fa': 'فلز پس\u200cواسطه',
  'group': 14,
  'group_text': '14',
  'period': 7,
  'config': '[Rn] 5f14 6d10 7s2 7p2',
  'mass': 289},
 {'z': 115,
  'symbol': 'Mc',
  'name': 'Moscovium',
  'name_fa': 'مسکوویم',
  'category': 'post-transition metal',
  'category_fa': 'فلز پس\u200cواسطه',
  'group': 15,
  'group_text': '15',
  'period': 7,
  'config': '[Rn] 5f14 6d10 7s2 7p3',
  'mass': 290},
 {'z': 116,
  'symbol': 'Lv',
  'name': 'Livermorium',
  'name_fa': 'لیورموریم',
  'category': 'post-transition metal',
  'category_fa': 'فلز پس\u200cواسطه',
  'group': 16,
  'group_text': '16',
  'period': 7,
  'config': '[Rn] 5f14 6d10 7s2 7p4',
  'mass': 293},
 {'z': 117,
  'symbol': 'Ts',
  'name': 'Tennessine',
  'name_fa': 'تنسین',
  'category': 'halogen',
  'category_fa': 'هالوژن',
  'group': 17,
  'group_text': '17',
  'period': 7,
  'config': '[Rn] 5f14 6d10 7s2 7p5',
  'mass': 294},
 {'z': 118,
  'symbol': 'Og',
  'name': 'Oganesson',
  'name_fa': 'اوگانسون',
  'category': 'noble gas',
  'category_fa': 'گاز نجیب',
  'group': 18,
  'group_text': '18',
  'period': 7,
  'config': '[Rn] 5f14 6d10 7s2 7p6',
  'mass': 294}]
COLORS = {'actinide': '#D8B6A4',
 'alkali metal': '#F7B7B7',
 'alkaline earth metal': '#F7D49B',
 'halogen': '#BFD7FF',
 'lanthanide': '#F2B7D8',
 'metalloid': '#C5E6A6',
 'noble gas': '#D9C2F0',
 'nonmetal': '#AEE4E8',
 'post-transition metal': '#FFF0A8',
 'transition metal': '#F6C98D'}
CATEGORY_FA = {'actinide': 'اکتینید',
 'alkali metal': 'فلز قلیایی',
 'alkaline earth metal': 'فلز قلیایی خاکی',
 'halogen': 'هالوژن',
 'lanthanide': 'لانتانید',
 'metalloid': 'شبه\u200cفلز',
 'noble gas': 'گاز نجیب',
 'nonmetal': 'نافلز',
 'post-transition metal': 'فلز پس\u200cواسطه',
 'transition metal': 'فلز واسطه'}

# More readable mobile palette derived from the desktop theme.
GLASS_BG = (0.95, 0.98, 1.0, 0.96)
GLASS_EDGE = (0.30, 0.72, 0.98, 0.90)
SHADOW = (0.18, 0.40, 0.65, 0.22)
BLUE_CARD = (0.78, 0.93, 1.0, 0.97)
PURPLE_CARD = (0.91, 0.82, 1.0, 0.98)
TEXT = (0.08, 0.16, 0.24, 1)
SUBTEXT = (0.25, 0.35, 0.45, 1)

# Kivy uses its own touch system; there is no normal desktop hover on Android.
# Therefore a tap is used as the mobile equivalent of the two tooltips.

NOBLE_GAS_CORES = {
    "[He]": "1s2",
    "[Ne]": "1s2 2s2 2p6",
    "[Ar]": "1s2 2s2 2p6 3s2 3p6",
    "[Kr]": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6",
    "[Xe]": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6",
    "[Rn]": "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6",
}

def expand_core(config):
    out=config
    for core,exp in NOBLE_GAS_CORES.items():
        out=out.replace(core,exp)
    return out

def parse_config(config):
    result=[]
    for token in expand_core(config).split():
        m=re.match(r"^(\d)([spdf])(\d+)$", token)
        if m:
            n,orb,count=m.groups(); result.append((int(n),orb,int(count)))
    return result

def sup(n):
    return str(n).translate(str.maketrans("0123456789-+", "⁰¹²³⁴⁵⁶⁷⁸⁹⁻⁺"))

def pretty_compact(config):
    result=[]
    for token in config.split():
        if token in NOBLE_GAS_CORES:
            result.append(token); continue
        m=re.match(r"^(\d)([spdf])(\d+)$", token)
        if m:
            n,orb,c=m.groups(); result.append(f"{n}{orb}{sup(c)}")
        else: result.append(token)
    return " ".join(result)

def group_calc(el):
    z=el['z']; period=el['period']; category=el['category']; parts=parse_config(el['config'])
    if z==2:
        return "۱) آرایش: 1s²\n۲) لایهٔ ظرفیت کامل است (۲ الکترون).\n۳) هلیم استثناست و در گروه ۱۸ قرار می‌گیرد.\nنتیجه: گروه ۱۸ (گاز نجیب)"
    s=sum(c for n,o,c in parts if n==period and o=='s')
    p=sum(c for n,o,c in parts if n==period and o=='p')
    d=sum(c for n,o,c in parts if n==period-1 and o=='d')
    f=any(o=='f' for n,o,c in parts)
    if category in ('lanthanide','actinide'):
        return "۱) عنصر در بلوک f است.\n۲) زیرلایهٔ f در آرایش الکترونی تکمیل می‌شود.\n۳) این عناصر در ردیف جداگانهٔ f نمایش داده می‌شوند.\nنتیجه: بلوک f — گروه عددی مستقلی در این نمایش ندارد."
    if p>0:
        g=12+p
        return f"۱) آرایش لایهٔ ظرفیت: {period}s{s} {period}p{p}\n۲) الکترون‌های ظرفیت = {s+p}\n۳) گروه = ۱۲ + تعداد الکترون‌های p = ۱۲ + {p} = {g}\nنتیجه: گروه {g}"
    if d>0 and period>=4:
        g=d+s
        return f"۱) زیرلایه‌های مؤثر: {period-1}d{d} {period}s{s}\n۲) الکترون‌های d = {d} و s = {s}\n۳) گروه = d + s = {d} + {s} = {g}\nنتیجه: گروه {g}"
    if s in (1,2):
        return f"۱) آرایش لایهٔ ظرفیت: {period}s{s}\n۲) الکترون‌های s = {s}\n۳) گروه = تعداد الکترون‌های s = {s}\nنتیجه: گروه {s}"
    return f"گروه ثبت‌شده در جدول: {el['group_text']}"

class GlassBox(RelativeLayout):
    bg = ListProperty(GLASS_BG)
    edge = ListProperty(GLASS_EDGE)
    radius = NumericProperty(dp(14))
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.size_hint_y=None
        self.bind(pos=self._redraw,size=self._redraw,bg=self._redraw,edge=self._redraw)
        self._redraw()
    def _redraw(self,*_):
        self.canvas.before.clear()
        with self.canvas.before:
            Color(*SHADOW)
            RoundedRectangle(pos=(self.x+dp(3),self.y-dp(3)),size=self.size,radius=[self.radius])
            Color(*self.bg)
            RoundedRectangle(pos=self.pos,size=self.size,radius=[self.radius])
            Color(*self.edge)
            Line(rounded_rectangle=(self.x,self.y,self.width,self.height,self.radius),width=dp(1.2))
            Color(1,1,1,0.48)
            RoundedRectangle(pos=(self.x+dp(5),self.y+self.height-dp(9)),size=(max(0,self.width-dp(10)),dp(3)),radius=[dp(2)])

class ElementCard(ButtonBehavior, RelativeLayout):
    def __init__(self, element, **kwargs):
        super().__init__(**kwargs)
        self.element=element
        self.size_hint=(None,None); self.size=(dp(92),dp(108))
        self.selected=False
        base=COLORS[element['category']]
        self.base=self._rgb(base)
        self.bind(pos=self._redraw,size=self._redraw)
        self._redraw()
        self.build_labels()
    @staticmethod
    def _rgb(hexv):
        hexv=hexv.lstrip('#'); return tuple(int(hexv[i:i+2],16)/255 for i in (0,2,4))+ (0.90,)
    def build_labels(self):
        e=self.element
        self.add_widget(Label(text=f"Z {e['z']}",font_size=sp(12),color=TEXT,size_hint=(None,None),size=(dp(40),dp(20)),pos=(dp(5),self.height-dp(25))))
        self.add_widget(Label(text=f"A {e['mass']}",font_size=sp(12),color=TEXT,size_hint=(None,None),size=(dp(47),dp(20)),pos=(self.width-dp(52),self.height-dp(25))))
        self.add_widget(Label(text=e['symbol'],font_size=sp(27),bold=True,color=TEXT,size_hint=(1,None),height=dp(38),pos=(0,dp(42))))
        self.add_widget(Label(text=e['name_fa'],font_size=sp(12),color=TEXT,size_hint=(1,None),height=dp(20),pos=(0,dp(23))))
        self.add_widget(Label(text=e['name'],font_size=sp(8.5),color=SUBTEXT,size_hint=(1,None),height=dp(16),pos=(0,dp(7))))
    def _redraw(self,*_):
        self.canvas.before.clear()
        c=tuple(min(1,x+0.13) for x in self.base[:3])+(0.95,) if self.selected else self.base
        with self.canvas.before:
            Color(0.16,0.36,0.58,0.26)
            RoundedRectangle(pos=(self.x+dp(3),self.y-dp(4)),size=self.size,radius=[dp(14)])
            Color(*c)
            RoundedRectangle(pos=self.pos,size=self.size,radius=[dp(14)])
            Color(0.30,0.72,0.98,0.85 if self.selected else 0.50)
            Line(rounded_rectangle=(self.x,self.y,self.width,self.height,dp(14)),width=dp(1.6 if self.selected else 1.0))
            Color(1,1,1,0.60)
            RoundedRectangle(pos=(self.x+dp(8),self.y+self.height-dp(11)),size=(self.width-dp(16),dp(4)),radius=[dp(2)])
    def on_press(self):
        self.selected=True; self._redraw()
    def on_release(self):
        App.get_running_app().show_element(self.element)

class LegendCard(GlassBox):
    def __init__(self,title,color,**kwargs):
        super().__init__(**kwargs); self.size=(dp(170),dp(72));
        self.add_widget(Label(text=title,font_size=sp(13),bold=True,color=TEXT,size_hint=(1,1)))
        self.bg=self._hex(color)
        self._redraw()
    def _hex(self,c):
        c=c.lstrip('#'); return tuple(int(c[i:i+2],16)/255 for i in (0,2,4))+(0.82,)

class InfoModal(ModalView):
    def __init__(self, element, **kwargs):
        super().__init__(**kwargs)
        self.background_color=(0.05,0.12,0.20,0.36)
        self.auto_dismiss=True
        root=BoxLayout(orientation='vertical',padding=dp(14),spacing=dp(10))
        root.size_hint=(0.95,0.85)
        info=GlassBox(bg=BLUE_CARD,edge=(0.18,0.62,0.98,0.90),radius=dp(18),size_hint=(1,None),height=dp(220))
        info.add_widget(Label(text=f"{element['symbol']} — {element['name_fa']} — {element['name']}",font_size=sp(20),bold=True,color=TEXT,size_hint=(1,None),height=dp(45),pos=(0,dp(165))))
        info.add_widget(Label(text=f"Z = {element['z']}     A = {element['mass']}\nگروه: {element['group_text']}     دوره: {element['period']}\nدسته: {element['category_fa']}\n\nآرایش الکترونی:\n{pretty_compact(element['config'])}",font_size=sp(15),color=TEXT,halign='left',valign='middle',text_size=(dp(330),None),size_hint=(1,1)))
        calc=GlassBox(bg=PURPLE_CARD,edge=(0.64,0.36,0.92,0.90),radius=dp(18),size_hint=(1,None),height=dp(255))
        calc.add_widget(Label(text="محاسبه گروه از روی آرایش الکترونی",font_size=sp(18),bold=True,color=(0.33,0.15,0.55,1),size_hint=(1,None),height=dp(42),pos=(0,dp(195))))
        calc.add_widget(Label(text=group_calc(element),font_size=sp(14),color=TEXT,halign='left',valign='middle',text_size=(dp(330),dp(190)),size_hint=(1,1)))
        close=Button(text="بستن",font_size=sp(15),size_hint=(1,None),height=dp(48),background_normal='',background_color=(0.20,0.57,0.88,1),color=(1,1,1,1))
        close.bind(on_release=lambda *_: self.dismiss())
        root.add_widget(info); root.add_widget(calc); root.add_widget(close)
        self.add_widget(root)

class PeriodicRoot(BoxLayout):
    def __init__(self, **kwargs):
        super().__init__(orientation='vertical',padding=dp(8),spacing=dp(8),**kwargs)
        self.add_widget(Label(text="جدول تناوبی — ۱۱۸ عنصر",font_size=sp(24),bold=True,color=TEXT,size_hint=(1,None),height=dp(46)))
        legend_scroll=ScrollView(do_scroll_y=False,size_hint=(1,None),height=dp(82),bar_width=dp(3))
        legend=BoxLayout(orientation='horizontal',spacing=dp(8),size_hint_x=None)
        cats=['alkali metal','alkaline earth metal','transition metal','post-transition metal','metalloid','nonmetal','halogen','noble gas','lanthanide','actinide']
        for c in cats:
            card=LegendCard(CATEGORY_FA[c],COLORS[c]); legend.add_widget(card)
        legend.width=sum([dp(178) for _ in cats])
        legend_scroll.add_widget(legend); self.add_widget(legend_scroll)
        outer_y=ScrollView(do_scroll_x=False,bar_width=dp(4),size_hint=(1,1))
        horiz=ScrollView(do_scroll_y=False,bar_width=dp(4),size_hint=(1,None),height=dp(9*112+20))
        grid=GridLayout(cols=18,rows=9,spacing=dp(5),padding=dp(6),size_hint=(None,None),width=18*dp(97)+15*dp(5),height=9*dp(113)+15*dp(5))
        # Build 7 main periods + 2 f-block rows.
        lookup={(e['period'],e['group']):e for e in ELEMENTS.values() if e['period']<=7 and e['category'] not in ('lanthanide','actinide')}
        for row in range(1,8):
            for col in range(1,19):
                e=lookup.get((row,col))
                grid.add_widget(ElementCard(e) if e else Widget(size_hint=(None,None),size=(dp(92),dp(108))))
        f_lookup={(e['period'],e['group']):e for e in ELEMENTS.values() if e['category'] in ('lanthanide','actinide')}
        for row,period in [(8,6),(9,7)]:
            for col in range(1,19):
                e=f_lookup.get((period,col)) if 4<=col<=17 else None
                grid.add_widget(ElementCard(e) if e else Widget(size_hint=(None,None),size=(dp(92),dp(108))))
        horiz.add_widget(grid); outer_y.add_widget(horiz); self.add_widget(outer_y)
        self.add_widget(Label(text="برای جزئیات عنصر، روی خانه ضربه بزنید.",font_size=sp(13),color=SUBTEXT,size_hint=(1,None),height=dp(32)))

class PeriodicTableAndroid(App):
    title='جدول تناوبی ۱۱۸ عنصر'
    def build(self):
        Window.clearcolor=(0.93,0.96,0.99,1)
        return PeriodicRoot()
    def show_element(self,element):
        InfoModal(element).open()

if __name__=='__main__':
    PeriodicTableAndroid().run()
